SELECT ID,
IF(P_ID IS NULL, 'ROOT', IF ((SELECT COUNT(*) FROM TREE WHERE P_ID = T.ID) > 0, 'INNER', 'LEAF'))
FROM TREE as T
ORDER BY ID


SELECT D.NAME, COUNT(E.ID)
FROM DEPARTMENT D LEFT JOIN
(SELECT DEPT_ID, COUNT(ID) AS NUM FROM EMPLOYEE GROUP BY DEPT_ID) E
ON D.ID = E.DEPT_ID
ORDER BY E.NUM DESC, D.NAME

SELECT D.NAME, COUNT(E.ID) AS NUM
FROM DEPARTMENT D LEFT OUTER JOIN EMPLOYEE E ON D.ID = E.DEPT_ID
GROUP BY D.NAME
ORDER BY NUM DESC, D.NAME

